name: Blank Issue
description: Create an issue with no predefined structure
labels: []
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Describe your issue here
    validations:
      required: false